version: 2.1
orbs:
  allure: ayte/allure@0.1.3
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  run-tests:
    docker:
      - image: cimg/node:16.15.0-browsers
        environment:
          # this enables colors in the output
          TERM: xterm
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 99.0.4844.51
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      # Make `allure` command available by installing dependencies from `ayte` orb
      - allure/install
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install npm dependencies
          command: npm install --save
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: node ./node_modules/@wdio/cli/bin/wdio.js
      - run:
          name: Generate Allure Report
          when: always
          # Run command from orb more info https://github.com/ayte-io/circle-ci-orb-allure
          command: allure generate allure-results
      - store_test_results:
          path: ./
      - store_artifacts:
          path: allure-report
workflows:
  ui-tests:
    jobs:
      - run-tests
